export const paths = {
  Index: "/",
  Login: "/login",
  Register: "/register",
  About: "/about-us",
  Training: "/training",
  Consultation: "/book-consultation",
  ConsultationPage: "/consultation",
  Marketplace: "/marketplace",
  Contact: "/contact",
  courseDetails: "/course",
  payment: "/payments",
  paymentSuccess: "/payments/successful",
  paymentCancelled: "/payments/cancelled",
  // Admin Section
  adminIndex: "/admin",
  adminDashboard: "/admin/dashboard",
  users: "/admin/users",
  addNewAdmin: "/admin/users/addNew",
  editAdmin: "/admin/users/edit",
  services: "/admin/services",
  addNewService: "/admin/services/addNew",
  editService: "/admin/services/edit",
  courses: "/admin/courses",
  addNewCourse: "/admin/courses/addNew",
 
};
