export const endpoints = {
  login: "api/secure/login",
  logout: "api/secure/logout",
  bookConsultation: "/api/consultation/book-consultation",
  applyForTraining: "/api/training/apply",
  sendContactMessage: "/api/contact/create",
  validateAuth: "/api/secure/validate",
  getAllUsers: "/api/user/getAll",
  addNewStaff: "/api/secure/addUser",
  getUser: "/api/user/getOne",
  updateUser: "/api/user/update",
  deleteUser: "/api/user/delete",
  addNewService: "/api/product/create",
  getAllServices: "/api/product/all",
  getOneServiceById: "/api/product/getOne",
  updateService: "/api/product/update",
  deleteService: "/api/product/delete",
};
